import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

metadata = sa.MetaData()

learners = sa.Table(
    "learners",
    metadata,
    sa.Column("learner_id", sa.String(128), primary_key=True),
    sa.Column("nickname", sa.String(100), nullable=False),
    sa.Column("email", sa.String(255), nullable=False),
    sa.Column("invite_code", sa.String(32), nullable=False, unique=True),
    sa.Column("invited_by_learner_id", sa.String(128), nullable=True),
    sa.Column(
        "account_type",
        sa.String(32),
        nullable=False,
        server_default=sa.text("'registered'"),
    ),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)
experience_codes = sa.Table(
    "experience_codes",
    metadata,
    sa.Column("code_id", sa.String(128), primary_key=True),
    sa.Column("code_hash", sa.String(64), nullable=False, unique=True),
    sa.Column("code_hint", sa.String(24), nullable=False),
    sa.Column("label", sa.String(100), nullable=False),
    sa.Column("max_uses", sa.Integer(), nullable=False),
    sa.Column("used_count", sa.Integer(), nullable=False),
    sa.Column("created_by_role", sa.String(64), nullable=False),
    sa.Column("revoked_by_role", sa.String(64), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
)
experience_code_redemptions = sa.Table(
    "experience_code_redemptions",
    metadata,
    sa.Column("redemption_id", sa.String(128), primary_key=True),
    sa.Column("code_id", sa.String(128), nullable=False),
    sa.Column("learner_id", sa.String(128), nullable=False, unique=True),
    sa.Column("username", sa.String(100), nullable=False),
    sa.Column("username_key", sa.String(100), nullable=False),
    sa.Column("login_count", sa.Integer(), nullable=False),
    sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=False),
)
email_verification_challenges = sa.Table(
    "email_verification_challenges",
    metadata,
    sa.Column("challenge_id", sa.String(128), primary_key=True),
    sa.Column("email", sa.String(255), nullable=False),
    sa.Column("code_hash", sa.String(64), nullable=False),
    sa.Column("code_salt", sa.String(32), nullable=False),
    sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
    sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
)
learner_sessions = sa.Table(
    "learner_sessions",
    metadata,
    sa.Column("token_hash", sa.String(64), primary_key=True),
    sa.Column("learner_id", sa.String(128), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
)
learner_profile_snapshots = sa.Table(
    "learner_profile_snapshots",
    metadata,
    sa.Column("learner_snapshot_id", sa.String(128), primary_key=True),
    sa.Column("snapshot", postgresql.JSONB(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
workflow_runs = sa.Table(
    "workflow_runs",
    metadata,
    sa.Column("workflow_run_id", sa.String(128), primary_key=True),
    sa.Column("learner_snapshot_id", sa.String(128), nullable=True),
    sa.Column("learner_id", sa.String(128), nullable=True),
    sa.Column("run_kind", sa.String(32), nullable=False),
    sa.Column("predecessor_run_id", sa.String(128), nullable=True, unique=True),
    sa.Column("workflow_version", sa.String(128), nullable=False),
    sa.Column("state", sa.String(32), nullable=False),
    sa.Column("stage", sa.String(32), nullable=True),
    sa.Column("checkpoint_id", sa.String(128), nullable=False),
    sa.Column("model_call_count", sa.Integer(), nullable=False),
    sa.Column("cost_usd", sa.Numeric(8, 4), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("calibration_fallback_approved", sa.Boolean(), nullable=False),
    sa.Column("difficulty_feedback_status", sa.String(32), nullable=False),
    sa.Column("difficulty_rating", sa.String(32), nullable=True),
    sa.Column("next_task_placeholder_id", sa.String(128), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)
run_task_refs = sa.Table(
    "run_task_refs",
    metadata,
    sa.Column("workflow_run_id", sa.String(128), primary_key=True),
    sa.Column("role", sa.String(32), primary_key=True),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("task_type", sa.String(32), nullable=False),
    sa.Column("content_version_id", sa.String(128), nullable=False),
    sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
)
run_task_completion_events = sa.Table(
    "run_task_completion_events",
    metadata,
    sa.Column("completion_event_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("completed_task_version", sa.Integer(), nullable=False),
    sa.Column("highest_hint_level", sa.SmallInteger(), nullable=False),
)
material_match_decisions = sa.Table(
    "material_match_decisions",
    metadata,
    sa.Column("decision_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("learner_snapshot_id", sa.String(128), nullable=False),
    sa.Column("candidate_version_ids", postgresql.JSONB(), nullable=False),
    sa.Column("selected_content_version_id", sa.String(128), nullable=False),
    sa.Column("policy_version", sa.String(128), nullable=False),
    sa.Column("conservative", sa.Boolean(), nullable=False),
    sa.Column("reason_codes", postgresql.JSONB(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
difficulty_feedback_events = sa.Table(
    "difficulty_feedback_events",
    metadata,
    sa.Column("feedback_event_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("rating", sa.String(32), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
next_task_placeholders = sa.Table(
    "next_task_placeholders",
    metadata,
    sa.Column("placeholder_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("planned_task_type", sa.String(32), nullable=False),
    sa.Column("reason_code", sa.String(64), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
learning_tasks = sa.Table(
    "learning_tasks",
    metadata,
    sa.Column("task_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("learner_snapshot_id", sa.String(128), nullable=False),
    sa.Column("task_type", sa.String(32), nullable=False),
    sa.Column("state", sa.String(32), nullable=False),
    sa.Column("state_before_pause", sa.String(32), nullable=True),
    sa.Column("highest_hint_level", sa.SmallInteger(), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)
task_material_assignments = sa.Table(
    "task_material_assignments",
    metadata,
    sa.Column("assignment_id", sa.String(128), primary_key=True),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("ordinal", sa.Integer(), nullable=False),
    sa.Column("content_id", sa.String(128), nullable=False),
    sa.Column("content_version_id", sa.String(128), nullable=False),
    sa.Column("content_hash", sa.String(64), nullable=False),
    sa.Column("rights_status", sa.String(32), nullable=False),
    sa.Column("difficulty_status", sa.String(32), nullable=False),
    sa.Column("reason_code", sa.String(64), nullable=False),
    sa.Column("eligible_when_assigned", sa.Boolean(), nullable=False),
    sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
)
task_annotations = sa.Table(
    "task_annotations",
    metadata,
    sa.Column("annotation_id", sa.String(128), primary_key=True),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("content_version_id", sa.String(128), nullable=False),
    sa.Column("kind", sa.String(32), nullable=False),
    sa.Column("paragraph_id", sa.String(128), nullable=False),
    sa.Column("span_start", sa.Integer(), nullable=False),
    sa.Column("span_end", sa.Integer(), nullable=False),
    sa.Column("text_quote", sa.Text(), nullable=False),
    sa.Column("text_hash", sa.String(64), nullable=False),
    sa.Column("user_explanation", sa.Text(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
task_grammar_challenges = sa.Table(
    "task_grammar_challenges",
    metadata,
    sa.Column("task_id", sa.String(128), primary_key=True),
    sa.Column("content_version_id", sa.String(128), nullable=False),
    sa.Column("challenge_id", sa.String(128), nullable=False),
    sa.Column("hint_revealed", sa.Boolean(), nullable=False),
    sa.Column("attempt_count", sa.Integer(), nullable=False),
    sa.Column("resolved", sa.Boolean(), nullable=False),
    sa.Column("last_submission_hash", sa.String(64), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
)
material_assignment_invalidations = sa.Table(
    "material_assignment_invalidations",
    metadata,
    sa.Column("invalidation_id", sa.String(128), primary_key=True),
    sa.Column("assignment_id", sa.String(128), nullable=False),
    sa.Column("reason_code", sa.String(64), nullable=False),
    sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=False),
)
attempt_versions = sa.Table(
    "attempt_versions",
    metadata,
    sa.Column("attempt_version_id", sa.String(128), primary_key=True),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("text", sa.Text(), nullable=False),
    sa.Column("content_hash", sa.String(64), nullable=False),
    sa.Column("independence", sa.String(32), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
ai_interventions = sa.Table(
    "ai_interventions",
    metadata,
    sa.Column("intervention_id", sa.String(128), primary_key=True),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("input_attempt_version_id", sa.String(128), nullable=False),
    sa.Column("hint_level", sa.SmallInteger(), nullable=False),
    sa.Column("intervention_type", sa.String(32), nullable=False),
    sa.Column("model_adapter", sa.String(64), nullable=False),
    sa.Column("prompt_version", sa.String(128), nullable=False),
    sa.Column("reason_code", sa.String(64), nullable=False),
    sa.Column("delivered_content", sa.Text(), nullable=False),
    sa.Column("content_hash", sa.String(64), nullable=False),
    sa.Column("result_status", sa.String(32), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
model_invocations = sa.Table(
    "model_invocations",
    metadata,
    sa.Column("invocation_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("input_attempt_version_id", sa.String(128), nullable=False),
    sa.Column("purpose", sa.String(64), nullable=False),
    sa.Column("adapter", sa.String(64), nullable=False),
    sa.Column("prompt_version", sa.String(128), nullable=False),
    sa.Column("outcome", sa.String(64), nullable=False),
    sa.Column("is_remote", sa.Boolean(), nullable=False),
    sa.Column("estimated_cost_usd", sa.Numeric(8, 4), nullable=False),
    sa.Column("actual_cost_usd", sa.Numeric(8, 4), nullable=False),
    sa.Column("latency_ms", sa.Integer(), nullable=False),
    sa.Column("output_hash", sa.String(64), nullable=False),
    sa.Column("focus", sa.String(32), nullable=True),
    sa.Column("evidence_start", sa.Integer(), nullable=True),
    sa.Column("evidence_end", sa.Integer(), nullable=True),
    sa.Column("evidence_hash", sa.String(64), nullable=True),
    sa.Column("rejection_code", sa.String(64), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
model_invocation_ledger = sa.Table(
    "model_invocation_ledger",
    metadata,
    sa.Column("invocation_key", sa.String(64), primary_key=True),
    sa.Column("tool_name", sa.String(128), nullable=False),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("request_hash", sa.String(64), nullable=False),
    sa.Column("status", sa.String(16), nullable=False),
    sa.Column("response_payload", postgresql.JSONB(), nullable=True),
    sa.Column("output_hash", sa.String(64), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)
revision_events = sa.Table(
    "revision_events",
    metadata,
    sa.Column("revision_event_id", sa.String(128), primary_key=True),
    sa.Column("task_id", sa.String(128), nullable=False),
    sa.Column("from_attempt_version_id", sa.String(128), nullable=False),
    sa.Column("to_attempt_version_id", sa.String(128), nullable=False),
    sa.Column("intervention_id", sa.String(128), nullable=True),
    sa.Column("result_status", sa.String(32), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
domain_events = sa.Table(
    "domain_events",
    metadata,
    sa.Column("event_id", sa.String(128), primary_key=True),
    sa.Column("event_type", sa.String(96), nullable=False),
    sa.Column("aggregate_id", sa.String(128), nullable=False),
    sa.Column("aggregate_version", sa.Integer(), nullable=False),
    sa.Column("payload", postgresql.JSONB(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
)
audit_events = sa.Table(
    "audit_events",
    metadata,
    sa.Column("audit_event_id", sa.String(128), primary_key=True),
    sa.Column("workflow_run_id", sa.String(128), nullable=False),
    sa.Column("actor_type", sa.String(32), nullable=False),
    sa.Column("action", sa.String(64), nullable=False),
    sa.Column("reason_code", sa.String(64), nullable=False),
    sa.Column("target_version", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
idempotency_records = sa.Table(
    "idempotency_records",
    metadata,
    sa.Column("idempotency_key", sa.String(128), primary_key=True),
    sa.Column("command_name", sa.String(96), nullable=False),
    sa.Column("request_hash", sa.String(64), nullable=False),
    sa.Column("response_reference", sa.String(160), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)
outbox_messages = sa.Table(
    "outbox_messages",
    metadata,
    sa.Column("message_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("topic", sa.String(96), nullable=False),
    sa.Column("aggregate_id", sa.String(128), nullable=False),
    sa.Column("payload", postgresql.JSONB(), nullable=False),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("attempt_count", sa.Integer(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
)

learning_asset_index = sa.Table(
    "learning_asset_index",
    metadata,
    sa.Column("asset_id", sa.String(128), primary_key=True),
    sa.Column("learner_id", sa.String(128), nullable=False),
    sa.Column("asset_kind", sa.String(32), nullable=False),
    sa.Column("display_title", sa.String(240), nullable=False),
    sa.Column("tag_index", postgresql.JSONB(), nullable=False),
    sa.Column("source_type", sa.String(32), nullable=False),
    sa.Column("source_title", sa.String(240), nullable=True),
    sa.Column("source_task_id", sa.String(128), nullable=True),
    sa.Column("source_annotation_id", sa.String(128), nullable=True),
    sa.Column("source_intervention_id", sa.String(128), nullable=True),
    sa.Column("vault_provider", sa.String(32), nullable=False),
    sa.Column("vault_id", sa.String(128), nullable=True),
    sa.Column("document_id", sa.String(128), nullable=True),
    sa.Column("relative_path", sa.Text(), nullable=True),
    sa.Column("document_uri", sa.Text(), nullable=True),
    sa.Column("content_hash", sa.String(64), nullable=True),
    sa.Column("document_updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("evidence_status", sa.String(32), nullable=False),
    sa.Column("evidence_count", sa.Integer(), nullable=False),
    sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("starred", sa.Boolean(), nullable=False),
    sa.Column("sync_status", sa.String(32), nullable=False),
    sa.Column("sync_error_code", sa.String(64), nullable=True),
    sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
)

obsidian_sync_connections = sa.Table(
    "obsidian_sync_connections",
    metadata,
    sa.Column("connection_id", sa.String(128), primary_key=True),
    sa.Column("learner_id", sa.String(128), nullable=False),
    sa.Column("secret_hash", sa.String(64), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
)

obsidian_learning_context = sa.Table(
    "obsidian_learning_context",
    metadata,
    sa.Column("context_id", sa.String(64), primary_key=True),
    sa.Column("learner_id", sa.String(128), nullable=False),
    sa.Column("connection_id", sa.String(128), nullable=False),
    sa.Column("source_key", sa.Text(), nullable=False),
    sa.Column("title", sa.String(240), nullable=False),
    sa.Column("asset_kind", sa.String(32), nullable=False),
    sa.Column("tags", postgresql.JSONB(), nullable=False),
    sa.Column("excerpt", sa.Text(), nullable=False),
    sa.Column("content_hash", sa.String(64), nullable=False),
    sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
)

agent_memory_events = sa.Table(
    "agent_memory_events",
    metadata,
    sa.Column("event_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("project_key", sa.String(64), nullable=False),
    sa.Column("learner_id", sa.String(128), nullable=False),
    sa.Column("agent_name", sa.String(128), nullable=False),
    sa.Column("operation", sa.String(16), nullable=False),
    sa.Column("provider", sa.String(32), nullable=False),
    sa.Column("invocation_key", sa.String(128), nullable=False),
    sa.Column("workflow_run_id", sa.String(128), nullable=True),
    sa.Column("task_id", sa.String(128), nullable=True),
    sa.Column("query_hash", sa.String(64), nullable=True),
    sa.Column("memory_ids", postgresql.JSONB(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
)

personalized_training_materials = sa.Table(
    "personalized_training_materials",
    metadata,
    sa.Column("material_id", sa.String(128), primary_key=True),
    sa.Column("learner_id", sa.String(128), nullable=False),
    sa.Column("title", sa.String(240), nullable=False),
    sa.Column("paragraphs", postgresql.JSONB(), nullable=False),
    sa.Column("focus_points", postgresql.JSONB(), nullable=False),
    sa.Column("source_context_ids", postgresql.JSONB(), nullable=False),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("active_workflow_run_id", sa.String(128), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

control_tool_policies = sa.Table(
    "control_tool_policies",
    metadata,
    sa.Column("project_key", sa.String(64), primary_key=True),
    sa.Column("tool_name", sa.String(160), primary_key=True),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("updated_by_role", sa.String(64), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

control_prompts = sa.Table(
    "control_prompts",
    metadata,
    sa.Column("project_key", sa.String(64), primary_key=True),
    sa.Column("prompt_id", sa.String(160), primary_key=True),
    sa.Column("prompt_version", sa.String(32), primary_key=True),
    sa.Column("owner", sa.String(80), nullable=False),
    sa.Column("purpose", sa.String(500), nullable=False),
    sa.Column("template_text", sa.Text(), nullable=False),
    sa.Column("variables", postgresql.JSONB(), nullable=False),
    sa.Column("model_policy", postgresql.JSONB(), nullable=False),
    sa.Column("status", sa.String(24), nullable=False),
    sa.Column("content_hash", sa.String(64), nullable=False),
    sa.Column("version", sa.Integer(), nullable=False),
    sa.Column("created_by_role", sa.String(64), nullable=False),
    sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
)

content_generation_jobs = sa.Table(
    "content_generation_jobs",
    metadata,
    sa.Column("job_id", sa.String(128), primary_key=True),
    sa.Column("status", sa.String(32), nullable=False),
    sa.Column("seed", sa.Integer(), nullable=True),
    sa.Column("pack_id", sa.String(160), nullable=False),
    sa.Column("pack_version", sa.String(64), nullable=False),
    sa.Column("output_directory", sa.Text(), nullable=False),
    sa.Column("manifest_path", sa.Text(), nullable=True),
    sa.Column("item_count", sa.Integer(), nullable=False),
    sa.Column("agent_reviewed_count", sa.Integer(), nullable=False),
    sa.Column("validation_errors", postgresql.JSONB(), nullable=False),
    sa.Column("requested_by_role", sa.String(64), nullable=False),
    sa.Column("published_by_role", sa.String(64), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("current_stage", sa.String(64), nullable=False),
    sa.Column("current_item_id", sa.String(160), nullable=True),
    sa.Column("progress_completed", sa.Integer(), nullable=False),
    sa.Column("progress_total", sa.Integer(), nullable=False),
    sa.Column("attempt_count", sa.Integer(), nullable=False),
    sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("langfuse_trace_id", sa.String(64), nullable=True),
    sa.Column("model_provider", sa.String(32), nullable=True),
    sa.Column("model_name", sa.String(128), nullable=True),
    sa.Column("prefect_task_run_id", sa.String(36), nullable=True),
)

content_generation_events = sa.Table(
    "content_generation_events",
    metadata,
    sa.Column("event_id", sa.BigInteger(), primary_key=True, autoincrement=True),
    sa.Column("job_id", sa.String(128), nullable=False),
    sa.Column("event_type", sa.String(64), nullable=False),
    sa.Column("stage", sa.String(64), nullable=False),
    sa.Column("agent_role", sa.String(64), nullable=True),
    sa.Column("item_id", sa.String(160), nullable=True),
    sa.Column("attempt", sa.Integer(), nullable=True),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("detail", postgresql.JSONB(), nullable=False),
    sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
)

content_worker_runtime = sa.Table(
    "content_worker_runtime",
    metadata,
    sa.Column("worker_id", sa.String(64), primary_key=True),
    sa.Column("state", sa.String(32), nullable=False),
    sa.Column("current_job_id", sa.String(128), nullable=True),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
)
