from enum import StrEnum


class PublicErrorCode(StrEnum):
    TEMPORARY_UNAVAILABLE = "TEMPORARY_UNAVAILABLE"
    SAVE_NOT_CONFIRMED = "SAVE_NOT_CONFIRMED"
    MATERIAL_REPLACED = "MATERIAL_REPLACED"
    CONTENT_NOT_ELIGIBLE = "CONTENT_NOT_ELIGIBLE"
    OBSIDIAN_CONNECTION_REQUIRED = "OBSIDIAN_CONNECTION_REQUIRED"
    OBSIDIAN_CONTEXT_REQUIRED = "OBSIDIAN_CONTEXT_REQUIRED"
    FEEDBACK_NEEDS_REVIEW = "FEEDBACK_NEEDS_REVIEW"
    BUDGET_LIMIT_REACHED = "BUDGET_LIMIT_REACHED"
    SESSION_CONFLICT = "SESSION_CONFLICT"
